version: "3.0"

networks:
  shared-services:
    external: true
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - "./.postgres-data/db:/var/lib/postgresql/data"
    networks:
      - shared-services
